export const CLA = 0xd7;

export const INS_GET_EXT_PUBLIC_KEY = 0x10;
export const INS_DERIVE_ADDRESS = 0x11;

export const ERRORS = {
  INVALID_REQUEST_PARAMETERS: "0x6e05",
  INVALID_STATE: "0x6e06",
  INVALID_DATA: "0x6e07",
  REJECTED_BY_POLICY: "0x6e10",
  ERR_UNSUPPORTED_ADDRESS_TYPE: "0x6e12",

  RE_SELECTED_ERRORS: /Ledger device:.*0x6e0[4-9]/,
};
